#!/system/bin/sh

MODDIR=${0%/*}

# Default configuration values
has_started=false
CURL=$(command -v curl || echo "$MODDIR/curl")
BFR_PID=/data/adb/box/run/box.pid
log_file="$MODDIR/modpes.log"
source $MODDIR/config.ini
TIMEOUT=${TIMEOUT:-10}
INTERVAL=${INTERVAL:-60}
MAX_RETRY=${MAX_RETRY:-3}
PING_URL=${PING_URL:-"https://www.gstatic.com/generate_204"}
AIRPLANE_MODE_RADIOS=${AIRPLANE_MODE_RADIOS:-"cell,bluetooth,nfc,wifi,wimax"}


# --- Functions ---
bfr_running() {
    if [[ ! -f $BFR_PID ]]; then
        return 1
    fi
    last_modified=$(stat -c %Y $BFR_PID)
    current_time=$(date +%s)
    time_diff=$(( current_time - last_modified ))
    if [ $time_diff -gt 30 ] && grep -q "/data/adb/box/" "/proc/$(cat $BFR_PID)/cmdline" 2>/dev/null; then
        return 0
    fi
    return 1
}

update_description() {
  sed -i "s/description=\[.*\]/description=\[$1\]/" "${MODDIR}/module.prop"
}

log_message() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> "$log_file"
}

toggle_airplane_mode() {
    log_message "[DEBUG] Cycling airplane mode"

    cmd connectivity airplane-mode enable
    #sleep 2
    cmd connectivity airplane-mode disable

    log_message "[INFO] Renewing iptables"
    $MODDIR/iptables renew
}



# Set airplane mode radios
settings put global airplane_mode_radios $AIRPLANE_MODE_RADIOS

# wait until mobile data active
while true; do
    if [[ -n $(dumpsys telephony.registry | grep "mDataConnectionState=2") ]]; then
        break
    else
        log_message "[INFO] Wait mobile data active..."
        sleep 3
    fi
done

# --- Run Main Loop ---
while true; do
    source $MODDIR/config.ini
    retries=0
    internet_available=false
    is_calling=$(dumpsys telephony.registry | grep -q "mCallState=2" && echo true || echo false)
 
    if $ENABLED && ! $is_calling && bfr_running; then
        if ! $has_started; then
            update_description "🚀 Service is running"
            has_started=true
        fi

        while [[ $retries -lt $MAX_RETRY ]]; do
            response=$($CURL --insecure --max-time $TIMEOUT -fsL -o /dev/null -w "%{http_code}" $PING_URL)
            if [ "$response" -ne 0 ]; then
                log_message "[INFO] Internet connection is available."
                internet_available=true
                sleep $INTERVAL
                break
            else
                log_message "[WARN] Retry check connection..."
                ((retries++))
                sleep 1
            fi
        done

        if ! $internet_available; then
            log_message "[INFO] No internet connection! Reset connection"
            toggle_airplane_mode

            log_message "[INFO] Wait until mobile data active..."
            until [[ -n $(dumpsys telephony.registry | grep "mDataConnectionState=2" | awk '{print $NF}') ]]; do sleep 1; done

            current_time=$(date +"%H:%M")
            update_description "🚀 Service is running | ⌛️ $current_time"
            log_message "[INFO] Re-check connection..."
        fi
    else
        update_description "⚠️ Service not running"
        log_message "[WARN] Service not running"
        sleep 2
    fi
done
